# Generated by Django 4.2.2 on 2023-06-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_galery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio_pen',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
